const products = [
  {
    id: 1,
    name: "❤️",
    description: "Г/Ц Блинчики с мясом вес, Россия",
    price: "44, 50 ₽",
    pricev2: "50,50 ₽",
    rating: 5,
    discount: 0,
    images: "./images/header_img/img_1.png",
    images1: "./images/header_img/rating.png",
  },
  {
    id: 2,
    name: "❤️",
    description: "Г/Ц Блинчики с мясом вес, Россия",
    price: 71,
    rating: 5,
    discount: 20,
    images: ["./images/header_img/milk.png"],
    images1: ["./images/header_img/rating.png"],
  },
  {
    id: 3,
    name: "❤️",
    description: "Г/Ц Блинчики с мясом вес, Россия",
    price: 88,
    rating: 5,
    discount: 20,
    images: ["./images/header_img/calbsa.png"],
    images1: ["./images/header_img/rating.png"],
  },
  {
    id: 4,
    name: "❤️",
    description: "Г/Ц Блинчики с мясом вес, Россия",
    price: 94,
    rating: 4.5,
    discount: 20,
    images: ["./images/header_img/calbsa.png"],
    images1: ["./images/header_img/rating.png"],
  },
];
