const products = [
  {
    id: 1,
    name: "Apple",
    category: "Fruit",
    description: "A round fruit with a red, green, or yellow ",
    price: 89,
    rating: 5,
    discount: 0,
    images: ["./products/1.svg", "./products/2.svg", "./products/3.svg"],
  },
  {
    id: 2,
    name: "Banana",
    category: "Fruit",
    description:
      "A long, curved fruit with a yellow skin and sweet, creamy white flesh.",
    price: 71,
    rating: 5,
    discount: 20,
    images: [
      "./products/2.svg",
      "./products/3.svg",
      "./products/4.svg",
      "./products/5.svg",
    ],
  },
  {
    id: 3,
    name: "Bread",
    category: "Bakery",
    description:
      "A staple food made from flour, water, and yeast, baked into a loaf.",
    price: 88,
    rating: 5,
    discount: 20,
    images: [
      "./products/3.svg",
      "./products/4.svg",
      "./products/5.svg",
      "./products/6.svg",
    ],
  },
  {
    id: 4,
    name: "Broccoli",
    category: "Vegetable",
    description:
      "A green vegetable with a tree-like appearance, known for its high nutrient content.",
    price: 94,
    rating: 4.5,
    discount: 20,
    images: [
      "./products/4.svg",
      "./products/5.svg",
      "./products/6.svg",
      "./products/7.svg",
    ],
  },
  {
    id: 5,
    name: "Carrot",
    category: "Vegetable",
    description:
      "A root vegetable with a crunchy texture and a sweet, earthy flavor.",
    price: 82,
    rating: 5,
    discount: 20,
    images: [
      "./products/5.svg",
      "./products/6.svg",
      "./products/7.svg",
      "./products/8.svg",
    ],
  },
  {
    id: 6,
    name: "Cheese",
    category: "Dairy",
    description:
      "A dairy product made from milk, with a variety of textures and flavors.",
    price: 91,
    rating: 3.5,
    discount: 50,
    images: [
      "./products/6.svg",
      "./products/7.svg",
      "./products/8.svg",
      "./products/9.svg",
    ],
  },
  {
    id: 7,
    name: "Chicken",
    category: "Meat",
    description:
      "A type of poultry, often used as a source of protein in meals.",
    price: 68,
    rating: 3.5,
    discount: 20,
    images: [
      "./products/7.svg",
      "./products/8.svg",
      "./products/9.svg",
      "./products/10.svg",
    ],
  },
  {
    id: 8,
    name: "Chocolate",
    category: "Dessert",
    description:
      "A sweet food made from cacao beans, used in a variety of desserts and confections.",
    price: 61,
    rating: 4.5,
    discount: 20,
    images: [
      "./products/8.svg",
      "./products/9.svg",
      "./products/10.svg",
      "./products/11.svg",
    ],
  },
  {
    id: 9,
    name: "Coffee",
    category: "Dessert",
    description:
      "A dark, bitter beverage made from roasted coffee beans, typically used as a pick-me-up.",
    price: 98,
    rating: 5,
    discount: 20,
    images: [
      "./products/9.svg",
      "./products/10.svg",
      "./products/11.svg",
      "./products/12.svg",
    ],
  },
  {
    id: 10,
    name: "Egg",
    category: "Dairy",
    description:
      "A oval-shaped reproductive body produced by birds, often used as a source of protein in meals.",
    price: 79,
    rating: 4.5,
    discount: 0,
    images: [
      "./products/10.svg",
      "./products/11.svg",
      "./products/12.svg",
      "./products/13.svg",
    ],
  },
  {
    id: 11,
    name: "Fish",
    category: "Meat",
    description:
      "A type of seafood, known for its omega-3 fatty acids and high protein content.",
    price: 89,
    rating: 3.5,
    discount: 50,
    images: [
      "./products/11.svg",
      "./products/12.svg",
      "./products/13.svg",
      "./products/14.svg",
    ],
  },
  {
    id: 12,
    name: "Grapes",
    category: "Fruit",
    description:
      "A small, sweet fruit that grows in clusters, often used in wine-making.",
    price: 61,
    rating: 4,
    discount: 20,
    images: [
      "./products/12.svg",
      "./products/13.svg",
      "./products/14.svg",
      "./products/15.svg",
    ],
  },
  {
    id: 13,
    name: "Hamburger",
    category: "Fast food",
    description:
      "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
    price: 87,
    rating: 5,
    discount: 0,
    images: [
      "./products/13.svg",
      "./products/14.svg",
      "./products/15.svg",
      "./products/16.svg",
    ],
  },
  {
    id: 14,
    name: "Hot dog",
    category: "Fast food",
    description:
      "A type of sausage served in a long roll, often used as a quick and convenient food.",
    price: 84,
    rating: 4.5,
    discount: 50,
    images: [
      "./products/14.svg",
      "./products/15.svg",
      "./products/16.svg",
      "./products/17.svg",
    ],
  },
  {
    id: 15,
    name: "Ice cream",
    category: "Dessert",
    description:
      "A frozen dessert made from cream, sugar, and flavorings, available in a variety of flavors.",
    price: 68,
    rating: 4.5,
    discount: 0,
    images: [
      "./products/15.svg",
      "./products/16.svg",
      "./products/17.svg",
      "./products/18.svg",
    ],
  },
  {
    id: 16,
    name: "Lemon",
    category: "Fruit",
    description:
      "A yellow citrus fruit with a tart, acidic flavor, often used in cooking and baking.",
    price: 74,
    rating: 3.5,
    discount: 0,
    images: [
      "./products/16.svg",
      "./products/17.svg",
      "./products/18.svg",
      "./products/19.svg",
    ],
  },
];
